config/routes.rb
App::Application.routes.draw do
  resources :list_items

  resources :wishlists

  resources :users

  root 'welcome#index'

  

end

app/models/list_item.rb
require 'uri'

class ListItem < ActiveRecord::Base
  belongs_to :wishlist

  validates :name, :length => { :minimum => 3, :maximum => 25 }, :presence => true
  validates :url, :format => { :with => URI.regexp }, :presence => true
  validates :notes, :length => { :minimum => 3, :maximum => 300 }
  validates :wishlist_id, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :wishlists, dependent: :destroy

  validates :first_name, :length => { :minimum => 2, :maximum => 20 }, :presence => true
  validates :last_name, :length => { :minimum => 2, :maximum => 25 }, :presence => true
  validates :email_address, :length => { :minimum => 6, :maximum => 100 }, :presence => true,
            :format => { :with => /\A[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}\z/, :message => 'must be a valid email address!' }
  validates :birthday, :presence => true
end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
  has_many :list_items, dependent: :destroy
  belongs_to :user

  validates :user, presence: true
  validates :description, :length => { :minimum => 3, :maximum => 160 }, :presence => true
  validates :title, :length => { :minimum => 3, :maximum => 50 }, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  before_action :set_list_item, only: [:show, :edit, :update, :destroy]

  # GET /list_items
  # GET /list_items.json
  def index
    @list_items = ListItem.all
  end

  # GET /list_items/1
  # GET /list_items/1.json
  def show
  end

  # GET /list_items/new
  def new
    @list_item = ListItem.new
  end

  # GET /list_items/1/edit
  def edit
  end

  # POST /list_items
  # POST /list_items.json
  def create
    @list_item = ListItem.new(list_item_params)

    respond_to do |format|
      if @list_item.save
        format.html { redirect_to @list_item, notice: 'List item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @list_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /list_items/1
  # PATCH/PUT /list_items/1.json
  def update
    respond_to do |format|
      if @list_item.update(list_item_params)
        format.html { redirect_to @list_item, notice: 'List item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /list_items/1
  # DELETE /list_items/1.json
  def destroy
    @list_item.destroy
    respond_to do |format|
      format.html { redirect_to list_items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list_item
      @list_item = ListItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_item_params
      params.require(:list_item).permit(:name, :url, :notes, :wishlist_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email_address, :birthday)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  before_action :set_wishlist, only: [:show, :edit, :update, :destroy]

  # GET /wishlists
  # GET /wishlists.json
  def index
    @wishlists = Wishlist.all
  end

  # GET /wishlists/1
  # GET /wishlists/1.json
  def show
  end

  # GET /wishlists/new
  def new
    @wishlist = Wishlist.new
  end

  # GET /wishlists/1/edit
  def edit
  end

  # POST /wishlists
  # POST /wishlists.json
  def create
    @wishlist = Wishlist.new(wishlist_params)

    respond_to do |format|
      if @wishlist.save
        format.html { redirect_to @wishlist, notice: 'Wishlist was successfully created.' }
        format.json { render action: 'show', status: :created, location: @wishlist }
      else
        format.html { render action: 'new' }
        format.json { render json: @wishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wishlists/1
  # PATCH/PUT /wishlists/1.json
  def update
    respond_to do |format|
      if @wishlist.update(wishlist_params)
        format.html { redirect_to @wishlist, notice: 'Wishlist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @wishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wishlists/1
  # DELETE /wishlists/1.json
  def destroy
    @wishlist.destroy
    respond_to do |format|
      format.html { redirect_to wishlists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wishlist
      @wishlist = Wishlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wishlist_params
      params.require(:wishlist).permit(:title, :description, :owner_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    "bootstrap", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "bootstrap-responsive", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class='navbar navbar-inverse navbar-fixed-top'>
    <div class='navbar-inner'>
      <div class='container'>
        <a class='brand' href='/'>wishlists!</a>
        <ul class='nav'>
          <li>
            <%= link_to 'users', users_path %>
          </li>
          <li>
            <%= link_to 'wishlists', wishlists_path %>
          </li>
          <li>
            <%= link_to 'list items', list_items_path %>
          </li>
        </ul>
      </div>
    </div>
  </div>


<div class="container">

  <%= yield %>

</div>

</body>
</html>

app/views/list_items/_form.html.erb
<%= form_for(@list_item) do |f| %>
  <% if @list_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list_item.errors.count, "error") %> prohibited this list_item from being saved:</h2>

      <ul>
      <% @list_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_field :notes %>
  </div>
  <div class="field">
    <%= f.label :wishlist_id %><br>
    <%= f.text_field :wishlist_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/list_items/edit.html.erb
<h1>Editing list_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @list_item %> |
<%= link_to 'Back', list_items_path %>

app/views/list_items/index.html.erb
<h1>list items</h1>

<table class='table table-hover'>
  <thead>
    <tr>
      <th>name</th>
      <th>url</th>
      <th>notes</th>
      <th>wishlist</th>
      <th colspan='3'>controls</th>
    </tr>
  </thead>

  <tbody>
    <% @list_items.each do |list_item| %>
      <tr>
        <td><%= list_item.name %></td>
        <td><%= list_item.url %></td>
        <td><%= list_item.notes %></td>
        <td><%= list_item.wishlist_id %></td>
        <td><%= link_to 'show', list_item, class: 'btn btn-mini btn-info' %></td>
        <td><%= link_to 'edit', edit_list_item_path(list_item), class: 'btn btn-mini btn-warning' %></td>
        <td><%= link_to 'destroy', list_item, class: 'btn btn-mini btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'new list item', new_list_item_path, :class => 'btn btn-success' %>

app/views/list_items/new.html.erb
<h1>new list_item</h1>

<%= render 'form' %>

<%= link_to 'Back', list_items_path %>

app/views/list_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @list_item.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @list_item.url %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @list_item.notes %>
</p>

<p>
  <strong>Wishlist:</strong>
  <%= @list_item.wishlist_id %>
</p>

<%= link_to 'Edit', edit_list_item_path(@list_item) %> |
<%= link_to 'Back', list_items_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email_address %><br>
    <%= f.text_field :email_address %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.date_select :birthday %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>all users</h1>

<table class='table table-hover'>
  <thead>
    <tr>
      <th>first name</th>
      <th>last name</th>
      <th>email address</th>
      <th>birthday</th>
      <th colspan='3'>controls</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email_address %></td>
        <td><%= user.birthday %></td>
        <td><%= link_to 'show', user, class: 'btn btn-mini btn-info' %></td>
        <td><%= link_to 'edit', edit_user_path(user), class: 'btn btn-mini btn-warning' %></td>
        <td><%= link_to 'destroy', user, class: 'btn btn-mini btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'new user', new_user_path, :class => 'btn btn-success' %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @user.email_address %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @user.birthday %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.erb
Login maybe?

app/views/wishlists/_form.html.erb
<%= form_for(@wishlist) do |f| %>
  <% if @wishlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wishlist.errors.count, "error") %> prohibited this wishlist from being saved:</h2>

      <ul>
      <% @wishlist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit nil, :class => 'btn btn-danger' %>
  </div>
<% end %>

app/views/wishlists/edit.html.erb
<h1>Editing wishlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @wishlist %> |
<%= link_to 'Back', wishlists_path %>

app/views/wishlists/index.html.erb
<h1>all wishlists</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Owner ID</th>
      <th colspan='3'>Controls</th>
    </tr>
  </thead>

  <tbody>
    <% @wishlists.each do |wishlist| %>
      <tr>
        <td><%= wishlist.title %></td>
        <td><%= wishlist.description %></td>
        <td><%= wishlist.user_id %></td>
        <td><%= link_to 'show', wishlist, class: 'btn btn-mini btn-info' %></td>
        <td><%= link_to 'edit', edit_wishlist_path(wishlist), class: 'btn btn-mini btn-warning' %></td>
        <td><%= link_to 'destroy', wishlist, class: 'btn btn-mini btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'new list', new_wishlist_path, :class => 'btn btn-success' %>

app/views/wishlists/new.html.erb
<h1>new wishlist</h1>

<%= render 'form' %>

<%= link_to 'back', wishlists_path %>

app/views/wishlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @wishlist.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @wishlist.description %>
</p>

<p>
  <strong>Owner ID:</strong>
  <%= @wishlist.user_id %>
</p>

<%= link_to 'Edit', edit_wishlist_path(@wishlist) %> |
<%= link_to 'Back', wishlists_path %>